### ISSUE TITLE
"Find Location" field on the reports submit page is broken

### ISSUE THREAD

**Issue by kamaulynder** [ushahidi/Ushahidi_Web#1005]
Steps to reproduce:-
1. In the submit report page, on the "find location" field, type in a location, e.g Nairobi, Kenya. 

Expected result: The location is found, plotted on the map and the "Location Name" field is populated.
Actual Result: A pop up appears saying, location not found, see --> http://grab.by/jwfE

**Comment by mrkoyote** [comment]
> out

Hi, I'm consulting you in what specific version
2.7.1 Beta Version
2.7.2 Bug Fix Release
2.7.4 Beta
