### ISSUE TITLE
Undefined offset: 1 error when uploading CSV report

### ISSUE THREAD

**Issue by waq2062** [ushahidi/Ushahidi_Web#1169]
Hi,

I am getting this error when I try to upload CSV report.

---

Runtime Message

An error was detected which prevented the loading of this page. If this problem persists, please contact the website administrator.

system/core/utf8/ucfirst.php [17]:
Undefined offset: 1

**Comment by GAWDS** [comment]
Arg. I'm on 2.7.4 and having this error again. 

CSV file is missing required column"INCIDENT TITLE"
CSV file is missing required column"INCIDENT DATE"

I downloaded an existing sample report csv so I could match the format exactly and now the upload fails.  How can this still be happening? I have both of those columns exactly as they appear in the error.
