### ISSUE TITLE
Many unwanted categories being created by RSS feeds

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/Ushahidi_Web#1314]
RSS feeds are generating loads of unwanted categories in deployments, likely related to functionality that was merged for auto creating categories in feeds (i.e. [1]). This is undesirable behavior for deployers who didn't know about this feature and have all of a sudden seen many (hundreds or more) new categories emerging in their admin panels.

This feature needs to be a setting, defaulting to off since this is currently unmanageable.

[1] https://github.com/HTSolution/Ushahidi_Web/commit/7674b309b8617c6d9372eecc04775571f65d21f3

**Comment by Lathasn** [comment]
Hi, the categories are automatically getting increased due to Hashtags or RSS feeds. My deployment is climatix.crowdmap.com Please help in resolving the issue
