### ISSUE TITLE
contact strana

### ISSUE THREAD

**Issue by ivanmuljevski** [ushahidi/Ushahidi_Web#1374]
Dobijam ovaj kod :-1: 
Kohana_404_Exception

application/controllers/contact.php [27]:

The page you requested, contact, could not be found.

Report This Issue To Ushahidi

Found a bug? Submit a bug report to the Ushahidi Github issues page- help us make Ushahidi better software -- Thanks!

**Comment by rickhenderson** [comment]
When viewing a map, clicking on the "Contact Us" link at the bottom of the screen brings up the 404 Web Page not found error for:
application/controllers/contact.php [27]:

And it gives a link which sends you to this GitHub bug reporting tool.

**Comment by brianherbert** [comment]
@rickhenderson In the settings for your deployment, you need to add a site email address. After that, this page will no longer 404.
