### ISSUE TITLE
Framework Error when trying to access Stats in Crowdmap

### ISSUE THREAD

**Issue by leapark** [ushahidi/Ushahidi_Web#1423]
bindup.crowdmap.com > stats  gives framework error since yesterday, March 8, 2015.
"application/models/stats.php [535]:"
Unknown Exception: Error number: 7 Error message: couldn't connect to host 

![frameworkerror_3_8_2015](https://cloud.githubusercontent.com/assets/2498749/6563355/c5ba8d56-c65d-11e4-9868-182718a092e0.png)

**Comment by juanlacueva** [comment]
I had the same issue. I had to modify part of the curl call to the stat server. I stop receiving that massage but many stats stopped  showing of course.

**Comment by brianherbert** [comment]
Hey guys, there was a configuration issue with our SSL certificate on the stats server which was causing it to be inaccessible. This has since been cleared up and you shouldn't be seeing this error anymore. Apologies for the inconvenience.
