### ISSUE TITLE
Bugs in collections in UI

### ISSUE THREAD

**Issue by daneasterman** [ushahidi/Ushahidi_Web#1453]
Hi there, when I click on collections there is a number of bug-like behaviour including: duplication of collection names, and when clicking on "edit" for the current collection, it takes you to another collection. I am trying to teach a new group of volunteers to use this product so I would be very grateful if you could fix these problems as soon as possible.
Many Thanks,
Daniel Easterman

**Comment by daneasterman** [comment]
Also I've noticed there is a bug with task descriptions not being saved at all even when explicitly clicking on the "save button" in the survey area.

**Comment by rjmackay** [comment]
Hi @daneasterman I think these are issue with Ushahidi v3 not v2? I've moved the issue over to the correct bug tracker here: https://github.com/ushahidi/platform/issues/1402

Whats your deployment URL? Are you hosting it yourself or using ushahidi.com?
If you're hosting yourself, what version are you running?

**Comment by daneasterman** [comment]
Hi Robbie, thanks for your reply to me here as well! The deployment URL is:
palestine-reports.ushahidi.io
We are not self-hosting, we are using ushahidi.com
Best,
Daniel
