### ISSUE TITLE
An unexpected authentication error occured. Please try again shortly.

### ISSUE THREAD

**Issue by JudeVizi** [ushahidi/Ushahidi_Web#1460]
I'm experiencing this error when I try to log in into my crowdmap profile. 
"auth.password.An unexpected authentication error occured. Please try again shortly."
I already cleared my browser's cookies but unfortunately the error still occurs. Please help me to fix this problem, it is very important and urgent.

**Comment by cypherinfo** [comment]
Hello, I confirm that issue for my crowdmap deployment 2.X
https://linkem.crowdmap.com
I invite you to help to fix it.
Thank you.
Giuseppe

**Comment by cypherinfo** [comment]
I have contacted one great person of Ushahidi< it is all right now :)

**Comment by JudeVizi** [comment]
Thank you very much, with that you helped me a lot. I'm greatful :)

**Comment by JudeVizi** [comment]
Unfortunately, yet again, I cannot log into my crowdmap account. :( 
The error message says: auth.password.Database is currently unavailable.

**Comment by aoduor** [comment]
Hey @JudeVizi we're looking into it.

**Comment by JudeVizi** [comment]
Thank you!!!

**Comment by abitor-josue** [comment]
hello, help me..
I just get right now the same error "• auth.password.An unexpected authentication error occured. Please try again shortly." when i try to login on my account  at https://allo1011togo.crowdmap.com

**Comment by rowasc** [comment]
This has been resolved. Closing. THanks folks
