### ISSUE TITLE
Error message when I log in the crowdmap!

### ISSUE THREAD

**Issue by cypherinfo** [ushahidi/Ushahidi_Web#1480]
Hello, congratulations on your recent improvements. I've noticed that when I try to log in the backend as admin https://linkem.crowdmap.com I get the following error message (see image). At the moment it is impossible to log in! I invite you to fix it, please.
Thank you. 

![Log in issue Ushahidi](https://user-images.githubusercontent.com/922409/54808969-1bf4d380-4c82-11e9-98c1-941fc0ba6842.png)

**Comment by tuxpiper** [comment]
This has been confirmed resolved
