### ISSUE TITLE
Submit Report "Find location" button not working

### ISSUE THREAD

**Issue by darrenp1824** [ushahidi/Ushahidi_Web#683]
The "find location" button on the submit report page - http://greatlakescommonsmap.org/reports/submit - on my deployment is not working since upgrading to Ushahidi 2.4.  When you click the button nothing happens (no error report or anything), which makes me think it is a problem with connecting to the API in some way, but I am unsure.  I am not a php developer, so I am not sure how to solve.  

Any help would be great, thanks!

**Comment by darkdoom** [comment]
Hi, I have 2 deployments, and the Find Location button is not working... and I have the same problem, when you click the button nothing happens... I have Ushahidi 2.7.4, any idea???
