### ISSUE TITLE
Account email verification not working (no email sent)

### ISSUE THREAD

**Issue by lbell** [ushahidi/Ushahidi_Web#795]
I just experienced this, and it was recently reported in the forums:

Email is not sent when "Require email varification" is set. Approving a user without that verification does not work. 

(I also think that adding a user in the backend while email varfication is set is failing as well - but I have not had a chance to replicate.)

Ushahidi 2.5

**Comment by Ziusking** [comment]
had the same problems and just got it fixed , my email was @outlook.com when i used @yahoo.com i received the verification email

**Comment by ZOLO2** [comment]
I've just opened a github account and email verification or: clicking the button or link in the email you send, fail miserably with a 404 error.
How can I avoid this Please?
Is it a bug?
am I doing something wrong?
thank you

**Comment by akhilbhardwaj23** [comment]
I am also encountering this problem. Trying to use my gmail address for verification but the mail does not arrive.

**Comment by Florious** [comment]
I encountered this problem where I received a verification code but when I started verifying there's nothing happen.

**Comment by YuanhuiHE** [comment]
Every time I signed in GitHub, I have received a message like this:

> **You don’t have any verified emails. We recommend verifying at least one email.**
> Email verification helps our support team verify ownership if you lose account access and allows you to receive all the notifications you ask for.

I click the 'verifying' link and then click the 'Resend' label,  it always shows me "Could not send email verification." But I don't why it could not send email verification. How to fix it?

**Comment by rjmackay** [comment]
@hyhrop we don't run github. I think you need to contact github's support instead https://github.com/contact

**Comment by GuiStorti** [comment]
I had the same issue while I was using hotmail/outlook. I fixed it by adding a email from Gmail to my list. 
Give it a try.

**Comment by hovek** [comment]
I am not getting mail on Outlook live mail.

**Comment by elnazz** [comment]
I have same problem. I am going to add my university email to my git account, but the verification code is not sent to my email. So maaad!!!
I need to install student developer for which I have to add my university email to the account. :(

**Comment by EmanSza** [comment]
This does not work with cdsbeo.on.ca why?

**Comment by shonil24** [comment]
> I have same problem. I am going to add my university email to my git account, but the verification code is not sent to my email. So maaad!!!
> I need to install student developer for which I have to add my university email to the account. :(

I have the similar issue.

**Comment by bibek-bhattacharya** [comment]
> I have same problem. I am going to add my university email to my git account, but the verification code is not sent to my email. 
> I need to install student developer for which I have to add my university email to the account. :(

Same issue.

**Comment by DonoghuevStevenson** [comment]
I reset my password which got me in without the Email verification step.  Next time I logged in using my Username rather than my Email address.  Abracadabra!

**Comment by DonoghuevStevenson** [comment]
Sorry I should say that my last comment did not include the fact that the password reset did require Email verification, but that was straighforward.

**Comment by jhillejan** [comment]
In my case (MS Outlook), it just happend today, that I found the device verification emails in my spam folder, so maybe also the email verification mails might be marked as spam. Maybe the spam detection does not like the "noreply" within "noreply@github.com".
