### ISSUE TITLE
Database Error  Mysqli.php [159]

### ISSUE THREAD

**Issue by emuchemi** [ushahidi/Ushahidi_Web#992]
Database Error

A database error occurred while performing the requested procedure. Please review the database error below for more information.
system/libraries/drivers/Database/Mysqli.php [159]:
Database error: Unknown column 'message.reporter_id' in 'where clause' - SELECT COUNT(*) AS `records_found`
FROM `mediaco7_message`
JOIN `mediaco7_reporter` ON (`mediaco7_message`.`reporter_id` = `mediaco7_reporter`.`id`)
WHERE mediaco7_message.message_type = 1 AND message.reporter_id='42'
AND `service_id` = '3'

**Comment by rcesarfs** [comment]
Hi there! I am using Kohana version and got the message: 

Erro de database: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'ufmg.ufmgincident.incident_date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - SELECT DATE_FORMAT(incident_date, '%Y-%c') AS dates FROM ufmgincident WHERE incident_active = 1 GROUP BY DATE_FORMAT(incident_date, '%Y-%c') ORDER BY incident_date

Could anyone help me, please?
